version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    # command: ${CMD:-bash -c "python manage.py runserver 0.0.0.0:8041"}
    container_name: meetups
    ports:
      - "8042:8041"